# model_name: mistralai/Mistral-7B-Instruct-v0.2
model_name: mistralai/Mistral-7B-v0.1
train_dataset_path: data/{topic_generator}/train/mistral_{scoring_name}_{answer_generator}.jsonl
fs_path: data/{dataset_name}/fs_shot.pkl
question_path: data/{topic_generator}/questions/mistral.pkl
model_path: model_checkpoints/{topic_generator}/mistral_{scoring_name}_{answer_generator}_top{filter_size}
result_path: test_results/{topic_generator}/mistral_{scoring_name}_{answer_generator}_top{filter_size}.txt
catastrophic_ds_path: data/catastrophic_ds/mistral_{ds_name}.jsonl
learning_rate: 5.0e-6
