base_model_name: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
sft_model_path: model_checkpoints/SFT/tinyllama_{answer_generator}
dpo_model_path: model_checkpoints/DPO/tinyllama_{answer_generator}
result_path: test_results/{mode}/tinyllama_{answer_generator}.txt
sft_answer_path: data/wiki/answer/tinyllama_sft_{answer_generator}.pkl
dpo_answer_path: data/wiki/answer/tinyllama_dpo_{answer_generator}.pkl
question_path: data/wiki/questions.jsonl
context_answer_path: data/wiki/context_answer.jsonl
sft_learning_rate: 2.0e-5
dpo_learning_rate: 1.0e-6
temperature: 1.0
