model_name: alignment-handbook/zephyr-7b-sft-full
train_dataset_path: data/{topic_generator}/train/zephyr_{scoring_name}_{answer_generator}.jsonl
fs_path: data/{dataset_name}/fs_shot.pkl
question_path: data/{topic_generator}/questions/zephyr.pkl
model_path: model_checkpoints/{topic_generator}/zephyr_{scoring_name}_{answer_generator}_top{filter_size}
result_path: test_results/{topic_generator}/zephyr_{scoring_name}_{answer_generator}_top{filter_size}.txt
