mode: dpo
eval_split: 0.1
bf16: true
beta: 0.5
do_eval: true
do_train: true
overwrite_output_dir: true
gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_prompt_length: 1024
optim: rmsprop
save_strategy: "no"
save_total_limit: null
seed: 42
report_to: tensorboard
push_to_hub: false