mode: sft
eval_split: 0.1
eval_steps: 500
dtype: bfloat16
bf16: true
do_eval: true
do_train: true
evaluation_strategy: steps
save_strategy: "no"
overwrite_output_dir: true
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 2.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_seq_length: 2048
max_grad_norm: 1.0
optim: adamw_torch
seed: 42
warmup_ratio: 0.1
report_to: tensorboard
push_to_hub: false
remove_unused_columns: true